/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as hackCoinFlipSol from "./HackCoinFlip.sol";
export type { hackCoinFlipSol };
export type { HackTelephone } from "./HackTelephone";
