/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICoinFlip,
  ICoinFlipInterface,
} from "../../../attack/HackCoinFlip.sol/ICoinFlip";

const _abi = [
  {
    inputs: [
      {
        internalType: "bool",
        name: "_guess",
        type: "bool",
      },
    ],
    name: "flip",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICoinFlip__factory {
  static readonly abi = _abi;
  static createInterface(): ICoinFlipInterface {
    return new Interface(_abi) as ICoinFlipInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ICoinFlip {
    return new Contract(address, _abi, runner) as unknown as ICoinFlip;
  }
}
