/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CoinFlipGuess__factory } from "./CoinFlipGuess__factory";
export { ICoinFlip__factory } from "./ICoinFlip__factory";
