/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as hackCoinFlipSol from "./HackCoinFlip.sol";
export { HackTelephone__factory } from "./HackTelephone__factory";
