/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as attack from "./attack";
export type { attack };
export type { CoinFlip } from "./CoinFlip";
export type { Fallback } from "./Fallback";
export type { Telephone } from "./Telephone";
export * as factories from "./factories";
export type { CoinFlipGuess } from "./attack/HackCoinFlip.sol/CoinFlipGuess";
export { CoinFlipGuess__factory } from "./factories/attack/HackCoinFlip.sol/CoinFlipGuess__factory";
export type { ICoinFlip } from "./attack/HackCoinFlip.sol/ICoinFlip";
export { ICoinFlip__factory } from "./factories/attack/HackCoinFlip.sol/ICoinFlip__factory";
export type { HackTelephone } from "./attack/HackTelephone";
export { HackTelephone__factory } from "./factories/attack/HackTelephone__factory";
export { CoinFlip__factory } from "./factories/CoinFlip__factory";
export { Fallback__factory } from "./factories/Fallback__factory";
export { Telephone__factory } from "./factories/Telephone__factory";
